sudo: false
dist: trusty
language: node_js
node_js:
- lts/*
branches:
  except:
  - gh-pages
addons:
  firefox: latest
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
before_script:
- npm install web-component-tester@^5.0.0
- npm install bower
- export PATH=$PWD/node_modules/.bin:$PATH
- bower install
script:
- xvfb-run wct --skip-plugin sauce
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then wct --plugin sauce --skip-plugin
  local; fi
after_success:
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then openssl aes-256-cbc -k "$DEPLOYSECRET"
  -in deploy.enc -out deploy_key -d; fi
- cd $TRAVIS_BUILD_DIR/scripts
- chmod 755 ghp.sh
- "./ghp.sh"
env:
  global:
  - secure: vk2C6cb9HptGxQP4WYa13V0rE0TmTaqLh9oB+jcZ3OouM9TTuReHxe6oTMOR+r0B+6W8nE6Hks6eSqadK7FtZ95dfvlxau4rYXO+5A97xApUFWO5NbBwD+khm9OftjQskzH8inbuXLdq3IzDm/Xb70qYlJGc3yHkeO0DheGrGcG3m+gAC4rmjAdi4+6pk1vq/gISbQ5o9umdqFymLdvfajH2aO6PiH+O1ePDkLr2u/KHawhKxGV6+5mIlrZbI8m3+A/grFQ7ruySQb5/VMAVZx1MiL+PzhypBBcNKCavSAS7XJov+OHv4rs7BOb8zQkFhW0DKM7ssclsCJrd6Owi3MmG5Yrik+EDnuhNxiucS4NvQExd1MeGWoipikZgtsP0xkv16LBJxGgDsn3nAgWQr6bXsdTWn+y3qlPDHsGDiNtMiamA0tCYmoBjEekKLsieNV4Xtjpg3pvvIKNSv7QzgeEBHgQigFnFFEoxXg9vwU1ZSvckMLpmUXE7nCsxW8Xahq5mkYlcgypQChGNetNXy96udZZ+ySMtCEJZVJgn+gW3szqnM28kmnfFSw2JIodSWnHd0sTq4HTUeiYu6lFioMI7YxWboPP55k5M5D/XeeO8D00K5r/5zzfZ5fJhyIKk8JJOybJbH6YhpKd8G1bUPACXFiN9pj+TIzTgHVDBk2Y=
  - secure: dG5Fjw9N7Kwa9VAfM9LJGsrWHcZ+jQguv4qu8jAnf7GH2YwWNO0talyu6GeYk5sg/I+FCe5FYjboD9g50Akf8abrgwafR8ivuROtzaSxMlVcCWjS22OaeRfbr30RdChIQ/ZTr9hvENwEIbiB424DlRwBI9PwR9Bn3QIFnDnto8537vYTpV9f00kDdUNnkSZWAnjaLKRUvEqX9olnCZDaukSsQt7KA9xKfZIX8KhZHu50P57X5Lv0wgGC1LEvUS0q98sHqNYxce/J6kiUucg22fMntOhDWGwXHW7sLNUDTVGEHxlM5QSnvLrX9WQ7sisIfODJaYfYncyOCDwk9nbAc59fe7XF67qbkfCal/qyAu1s2Mstvk24W53ZAIA76rVAu5U66134lxVpIGCvisDggWlsw1dvx5RUjU/t2vw4cX2W+OP5/eEuSu+izAaB4/EU29WkT4r+bgTogsTyAab96q9cMOsqO5LslnbBqyoM/0et7ljG2gUF78hGbvdEw6HX0F7Zy6Y0WeAubM+tzSa7/f/8trJRJEYjiI4TTGFUCZxHk+YrvODacKfBf/ta9EubglmK1LBx0PzGanVr0jikJgWNaY4NHwWjN6hygkXkUI9lB67NTBBhFHGcEMI0bVo9zpjAFEba7U/7QF83kBVGkVj0Ia3Tv66SJ0Zvhu6ALyY=
  - secure: Jo2H4LCsD+w/dEdxGel+6zE1sSMvpznImG399RKY/EDwpPo670MCPCeBQDVegM7nF/yffEs+mBGSrEPlsE5OLQtsrzgQdlXsvFog4JB9OT9PkgTofgmBQDb24VZgk6+bH9+e4y0Y5dR+ksnZP7F6BSupFAMBtBinkdygnrdj16fLbRx2nKs+XaeoSObNBfSbL6tSVpvqlqcwocZWO1y4k8Ya0ChHU/5w/ZdHz6VpsN5EYhm9Yhb2qtUDhmYrWjc1ybJHfW6AHljy6HO3q5pi4wHDD6zEv9SkHEnHnQoX3GeGipEz/TGVdfZdvRtAxDnJ5KKId7EhlQ/LfKI33s0nm2b/sOXe/V/QPHYpglvHcH4aFSWolRdsUr4tXVqYqDzmQZjvraNxb+d4pgKDh03Q5KHeRX6bFjj+bbpIWD12v2RQ3Dy0mYJH0V8SqBf4u0BnyHULNOdfoDzovonTduegVHf+spYfiil4ZMzl57SWJ6fDGttz7FaqLllF+ISKGOcay7vkZycwxbTt49/IJUBY0R+yJKrx2Vjni854KATD6Rtaezrr2erhsmCYC+clBFQcIw5mKoFUQyyU7oPG5R7O+Zyok2xGS4935xfNSUKesrzrxKQzXoZWUwGpLa/pdc+OaoR3liHoyxJUuUXSsd6IgBZiROW/LmSuuyNbbKkYAso=
  - secure: UOQWVcUY53s7s74/8riIF2du2GfjCwOxj4JfjOvSpvD97poTZYMg4NA32tLAyMvu5zunxdRMavaQOJEuQYspHDSXz9o5ebgpYkcEkiom1XF2lqbV9PGeQliNKDfyCeaYAo4JQ40BnIvCfNesBhyZc8frh6GzTRna/6Ak982ecWFDzCC4a4LglfnzP2RzwvNXAhp5qM65ydAEXyCgOblO5+G4/F8dgoBWJI1BbeNOl57H8/G56tF8dEJ9FnbMV630IHF/HE4ruD5WtSKVhxHhVBkSf14lDWvvAkQnGARoYpptOSeDF3bQ43DZ3tOwfUkeJf+9ZtvNkWHMxdy2XSB4CYCx6uMyZjfnBYmtqAsQQ3EItHO4X7nATcFXd10apG60pZ9EzB3bx0DmlY3VMitD3QrXbHBYAviJcxxbvKS2K/iQAbe1MjlDFuaIM8PKO/wEuiZyEhgcVKyiWKWMOpYMlWms2h0J+mJXRcZuuDRA18Znwtqxv2/gwmoMcUIAZ7gB2vmEUmuIeJ/4sPp34JiNSnruTYYeWEw37S/Qo9mT1sYJRTfnSTxizq8S/6ZWmUn4oRngqnLaJyrLsqwdsfoDL7/BuHCvVgSVwdiwgXMvfxm8qNdpXfCdoHfLsu468OTggEUkMpiaE9Rvu7d42rffv9T35kVDg+SQrLYE265GRH0=
